name: 'F1_Data_Analysis'

config-version: 2
version: '0.1'

profile: 'formula_one'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests", "data-tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  formuala_one:
      materialized: table
      staging:
        materialized: view
